version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: pullveryzator/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    env_file: .env
    image: pullveryzator/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
      # - ./frontend/:/app/result_build/
  gateway:
    env_file: .env
    image: pullveryzator/foodgram_gateway
    command: cp -r /app/docs/. /staticfiles/
    ports:
      - 9500:80
    volumes:
      - static:/staticfiles
      - media:/media
      # - ./frontend/build:/usr/share/nginx/html/
      # - ./docs/:/usr/share/nginx/html/api/docs/
