# Generated by Django 3.2.3 on 2024-06-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240613_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientinrecipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
