# Generated by Django 3.2.3 on 2024-06-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
